# Generated by Django 3.1.2 on 2020-10-31 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_certificate_project_workexperience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='workexperience',
            old_name='discription',
            new_name='description',
        ),
    ]
